services:
  asterisk:
    image: andrius/asterisk:22
    container_name: asterisk
    restart: unless-stopped
    networks:
      - asterisk_net
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "10000-10100:10000-10100/udp"
    volumes:
      - ./asterisk_conf/pjsip.conf:/etc/asterisk/pjsip.conf:ro
      - ./asterisk_conf/extensions.conf:/etc/asterisk/extensions.conf:ro
      - ./asterisk_conf/rtp.conf:/etc/asterisk/rtp.conf:ro
      - ./asterisk_conf_sounds:/var/lib/asterisk/sounds:ro
      - ./asterisk_logs:/var/log/asterisk

networks:
  asterisk_net:
    driver: bridge
